routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});


Auth::routes();

Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::middleware('auth')->group(function(){


    Route::resource('requests', 'ResRequestController');
    Route::view('addRequest','requests/addRequest')->name('addRequest');
    Route::resource('season','SeasonController');
    Route::get('home', 'PresenterController@index')->name('home');
    Route::post('requests-add', 'ResRequestController@getSeasonWeeks')->name('getSeasonWeeks');
    Route::resource('tourTeams', 'TourTeamsController');
    Route::delete('tourTeams', 'TourTeamsController@delete');
    Route::resource('presenters', 'PresenterController');
    Route::resource('contacts', 'ContactController');
    Route::resource('shows','ShowController');
    Route::resource('bookings','BookingController');
    // route::route('bookings','BookingController');
    Route::post('moveBooking', 'BookingController@moveBooking')->name('moveBooking');
    Route::get('createBooking/{seasonId}/{weekId?}/{tourTeamId?}', [
        'as' => 'createBooking', 'uses' => 'BookingController@createBooking']);
    Route::get('deleteBooking/{id}', [
            'as' => 'deleteBooking', 'uses' => 'BookingController@deleteBooking']);
    Route::view('admin','admin')->name('admin');
    Route::view('edit_request','edit_request')->name('edit_request');

});

Route::get('test','Controller@index');

resources/views/addBooking.blade.php
@extends('layouts.master')

@section('title')
    Add Booking Page
@endsection
@section('assets')
<style>
    div.request-tile
    {
            width:400px;
            color:black;
            position: relative;
            border-radius: 5px;
            text-align: center;
    }
</style>
@endsection
@section('content')

<div class="container-fluid">
    <div class="row">
        <form class="form" id="new-booking" method="post" action="{{route('bookings.store')}}">
            {{ csrf_field() }}
            <div class="col-sm-3 control-label" class="form-group mb-2" style="width:100%">
                <h3>Reservation Request:</h3>
                {{-- <div  name="request" id="selectedRequest" >
                    Select Request                    
                </div> --}}
                <button class="btn btn-primary btn-lg" type="button" role="button" data-toggle="modal" data-target="#selectRequest" >Select Request</button>
                
            </div>
        <br>
        <br>
        <br>
        <br>
            <div class="form-group mb-2">
                <label class="col-sm-3 control-label" for="bookingWeek">Week:</label>
                <select name="bookingWeek" id="bookingWeek" class="form-control"
                        aria-controls="help-pickup">

                        <option value="" disabled="disabled" {{$weekId==null?'selected="selected"':""}}>Select week</option>

                        @foreach ($season->weeks as $week)
                            <option value='{{$week->id}}' {{$weekId==$week->id?'selected="selected"':""}}>
                                    {{\App\Models\Week::displayDates($week->start_date,$week->end_date)}}
                            </option>
                        @endforeach
                    </select>
            </div>
            <div class="form-group mb-2">
                    <label class="col-sm-3 control-label" for="bookingTourTeam">Show:</label>
                    <select name="bookingTourTeam" id="bookingTourTeam" class="form-control"
                            aria-controls="help-pickup">
                            <option value="" disabled="disabled" {{$tourTeamId==null?'selected="selected"':""}}>Select show</option>
                        @foreach ($season->tour_teams as $tourTeam)
                            <option value='{{$tourTeam->id}}' {{$tourTeamId==$tourTeam->id?'selected="selected"':""}}>
                                    {{\App\Models\Tour_team::display($tourTeam)}}
                            </option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group mb-2">
                        <label class="col-sm-3 control-label" for="bookingStatus">Status:</label>
                        <select name="bookingStatus" id="bookingStatus" class="form-control"
                            aria-controls="help-pickup">
                                <option value="">Select status</option>
                            @foreach ($bookingStatuses as $bookingStatus)
                                <option value='{{$bookingStatus->id}}' title="{{$bookingStatus->description}}">
                                        {{$bookingStatus->name}}
                                </option>
                            @endforeach
                        </select>
                    </div>

            <div class="form-group col-md-12">
                <input type="hidden" readonly class="form-control-plaintext" name="complete" id="complete"
                       value = 0>
            </div>

            <a href="{{route('season.show',$season->id)}}" type="button" class="btn btn-secondary" >Cancel</a>
            <button type="submit" class="btn btn-primary" onclick="return validInputs()">OK</button>
        </form>
    </div>
    <div id="selectRequest" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title" id="exampleModalLabel">Select Request</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        @if($requests!=null)    
                        @foreach($requests as $request)
                        <div style="float:right;top">
                            <button onclick="selectRequest(requestTileParent{{$request->id}})" type="reset" class="btn btn-primary" data-dismiss="modal" class="btn btn-default" >Select</button>
                        </div>
                        <div id="requestTileParent{{$request->id}}" style="padding:5px;">
                        <div id="requestTile{{$request->id}}" class="request-tile" style="background-color:#{{$request->presenter->primary_contact->first()->state->region->color}}">
                            <div style="font-size: 1.6em;font-weight: bold;">
                                {{$request->presenter->primary_contact->first()->city.', '.$request->presenter->primary_contact->first()->state->abbreviation}}
                            </div>
                            <div style="font-size: .7em;">
                                {{$request->presenter->presenter_name}}
                            </div>
                            <div>
                                {{-- {{dd($request->availableWeeks)}} --}}
                                @foreach($request->availableWeeks as $week)
                                @if($loop->index == 0)
                                {{\App\Models\Week::displayDates($week->start_date,$week->end_date)}}
                                @else
                                {{', '.\App\Models\Week::displayDates($week->start_date,$week->end_date)}}
                                @endif
                                @endforeach
                            </div>
                        <input type="hidden" class="form-control-plaintext" name="hfRequestId" id="hfRequestId" value="{{$request->id}}">
                        </div>
                        </div>
                        @endforeach
                        @else
                            <div>No Requests for given date.</div>
                        @endif
                        @if($otherRequests!=null)
                            <hr/>
                            <h4>Requests not for date and show.</h4>
                            <div>
                                @foreach($otherRequests as $otherRequest)
                                <div style="float:right;top">
                                    <button onclick="selectRequest(requestTileParent{{$otherRequest->id}})" type="reset" class="btn btn-primary" data-dismiss="modal" class="btn btn-default">Select</button>
                                </div>
                                <div id="requestTileParent{{$otherRequest->id}}" style="padding:5px;">
                                <div id="requestTile{{$otherRequest->id}}" class="request-tile" style="background-color:#{{$otherRequest->presenter->primary_contact->first()->state->region->color}}">
                                    <div style="font-size: 1.6em;font-weight: bold;">
                                        {{$otherRequest->presenter->primary_contact->first()->city.', '.$otherRequest->presenter->primary_contact->first()->state->abbreviation}}
                                    </div>
                                    <div style="font-size: .7em;">
                                        {{$otherRequest->presenter->presenter_name}}
                                    </div>
                                    <div>
                                        {{-- {{dd($otherRequest->availableWeeks)}} --}}
                                        @foreach($otherRequest->availableWeeks as $week)
                                        @if($loop->index == 0)
                                        {{\App\Models\Week::displayDates($week->start_date,$week->end_date)}}
                                        @else
                                        {{', '.\App\Models\Week::displayDates($week->start_date,$week->end_date)}}
                                        @endif
                                        @endforeach
                                    </div>
                                <input type="hidden" class="form-control-plaintext" name="hfRequestId" id="hfRequestId" value="{{$otherRequest->id}}">
                                </div>
                                </div>
                                @endforeach
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
</div>

@endsection

@section('scripts')
<script>
    function selectRequest(tileName)
    {
      var secondDivContent = document.getElementById('selectedRequest');
      //secondDivContent.outerHTML = tileName.outerHTML;
      secondDivContent.innerHTML = tileName.innerHTML;
    }
    function validInputs()
    {
        if ($('#bookingWeek').val()==null)
        {
            alert("Please select a week.");
            return false;
        }
        if ($('#bookingTourTeam').val()==null)
        {
            alert("Please select a show.");
            return false;
        }
        if ($('#bookingStatus').val()==null)
        {
            alert("Please select a status.");
            return false;
        }
        if($('#selectedRequest').find('input[name="hfRequestId"]').val()==null)
        {
            alert("Please select a request");
            return false;
        }
        return true;
    }
</script>
@endsection

resources/views/admin.blade.php
@extends('layouts.master')

@section('title')
    Admin Page
@endsection

@section('content')
    <p>You are now logged in.</p>
@endsection

@section('scripts')

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/presenters.blade.php
@extends('layouts.master')

@section('title')
    Presenters Page
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <table class="table table-condensed table-striped table-bordered" id="tours-table" style="border-width: thick">
            <thead>
            <tr>

                <th>Presenter</th>
                <th>Contact Name</th>
                <th>Email</th>
                <th>Address</th>
                <th>City</th>
                <th>Zip Code</th>
                <th>State</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($presenters as $presenter)
                <tr>
                    <td>{{$presenter->presenter_name}}</td>
                    <td>{{$presenter->primary_contact->first() ? $presenter->primary_contact->first()->contact_name : ""}}</td>
                    <td>{{$presenter->primary_contact->first() ? $presenter->primary_contact->first()->email : ""}}</td>
                    <td>{{$presenter->primary_contact->first() ? $presenter->primary_contact->first()->address : ""}}</td>
                    <td>{{$presenter->primary_contact->first() ? $presenter->primary_contact->first()->city : ""}}</td>
                    <td>{{$presenter->primary_contact->first() ? $presenter->primary_contact->first()->zip_code : ""}}</td>
                    <td>{{$presenter->primary_contact->first() ? $presenter->primary_contact->first()->state->abbreviation : ""}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('table').DataTable({});
        });
    </script>
@endsection

resources/views/requests.blade.php
@extends('layouts.master')

@section('title')
    Request Page
@endsection

@section('head')

@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <form class="form-inline" id="search-bar" role="search">
            <div class="input-group add-on">
                <input class="form-control" placeholder="Presenter Name" name="srch-term" id="srch-term" type="text">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        </form>
    </div>

    <div class="row">
        <table class="table table-condensed table-striped table-bordered" id="tours-table" style="border-width: thick">
            <thead>
            <tr>
                <th>Presenter</th>
                <th>Season</th>
                <th>Number Weeks Required</th>
                <th>Consecutive Weeks</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($requests as $request)
                <tr>
                    <td>{{$request->presenter->presenter_name}}</td>
                    <td>{{$request->season->name}}</td>
                    <td>{{$request->num_wks_req}}</td>
                    <td>{{$request->consecutive_wks ==1 ? 'Yes':'No'}}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>

@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('table').DataTable({});
        });
    </script>
@endsection

resources/views/selectResRequestWeeks.blade.php
@extends('layouts.master')

@section('title')
    Edit Request Page
@endsection

@section('content')

    <div class="container-fluid">

        <div class="row">
            <div class="col-lg-12">

                <h2>Available Weeks</h2>

                <div class="form-group">
                    <div class="col-sm-3 control-label" for="season">Season:</div>
                    <div class="col-sm-9">
                        {{$season->name}}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-3 control-label" for="presenter">Presenter:</div>
                    <div class="col-sm-9">
                        {{  $presenter->presenter_name}}
                    </div>
                </div>

                <div class=form-group>
                    <div class="col-sm-3 control-label" for="number-weeks">Number of Weeks:</div>
                    <div class="col-sm-9">
                        {{$request->num_wks_req}}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-3 control-label" for="consecutive-weeks">Consecutive Weeks:</div>
                    <div class="col-sm-9">
                        {{$request->consecutive_wks==1 ? 'Yes':'No'}}
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <form class="form-horizontal" method="post" action="{{route('requests.store')}}">
                {{ csrf_field() }}
                <div class="col-md-3" style="height: 250px;">

                    <?php $month = ''; ?>
                    @foreach($season->weeks as $week)
                        @if($month != $week->start_date->format('F'))
                            <?php $month = $week->start_date->format('F') ?>
                            @if(!$loop->first)
                </div>
                <div class="col-md-3" style="height: 250px;">
                    @endif

                    <h3>{{$month}}</h3>


                    @endif
                    <div class="form-check">
                        <input class="form-check-input" name="weeks[{{$week->id}}]" type="checkbox"
                               value="{{$week->id}}"
                               id="Week-{{$week->id}}">
                        <label class="form-check-label" for="Week-{{$week->id}}">
                            {{$week->start_date->format('M, d')}} - {{$week->end_date->format('M, d')}}
                        </label>
                    </div>


                    @endforeach
                </div>
                <div class="form-group col-md-12">
                    <input type="hidden" readonly class="form-control-plaintext" name="season" id="season"
                           value="{{$season->id}}">
                    <input type="hidden" readonly class="form-control-plaintext" name="presenter" id="presenter"
                           value="{{$presenter->id}}">
                    <input type="hidden" readonly class="form-control-plaintext" name="number-weeks" id="number-weeks"
                           value="{{$request->num_wks_req}}">
                    <input type="hidden" readonly class="form-control-plaintext" name="consecutive-weeks"
                           id="consecutive-weeks"

                           {{--@if($request->consecutive_wks == 0)
                           value="NO"
                           @else
                           value="Yes"
                            @endif--}}
                           value="{{$request->consecutive_wks}}"
                    >
                    <!-- <button type="reset" role="button" class="col-sm-2 button btn btn-primary">Cancel</button> -->
                    <button type="submit" role="button" class="col-sm-2 button btn btn-primary pull-right">
                        Add
                    </button>
                </div>

        </div>
        </form>
    </div>

@endsection

@section('scripts')

@endsection

resources/views/selectSeason.blade.php
@extends('layouts.master')

@section('title')
    Season Page
@endsection

@section('content')
    <div class="row">
        {{--<form class="form-inline" id="season-form" method="post" action="">
            <div class="form-group mb-2">

                <label class="sr-only" for="season">Season Select:</label>
                <select name="season" id="season" class="form-control">
                    <option value="none">2017-18 School Year Season</option>
                </select>
            </div>
            <div class="form-group mb-2">
                <label for="week">Week:</label>

                <select name="week" id="week" class="form-control">
                    <option value="none">September 4-9</option>
                </select>
            </div>
            <div class="form-group mb-2">
                <label for="show"> Show:</label>

                <select name="show" id="show" class="form-control" aria-controls="help-pickup">
                    <option value="none">ALA-1</option>
                </select>
            </div>
            <button type="submit" role="button" class="col-sm-1 btn btn-primary pull-right">Options</button>
        </form>

        <form class="form-inline" id="search-bar" role="search">
            <div class="input-group add-on">
                <input class="form-control" placeholder="Search" name="srch-term" id="srch-term" type="text">
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        </form>--}}

        {{--TODO: fix button--}}
        <button type="button" role="button" data-toggle="modal" data-target="#newSeasonPopup" class="col-sm-1 btn-lg btn-primary btn-circle pull-right glyphicon glyphicon-plus"></button>
    </div> 

    <div class="row">
        @foreach($seasons as $season)
            <div class="panel panel-default">
                <div class="panel-heading" style="overflow:hidden;">
                    <div class="btn-toolbar pull-left btn-group">
                      <a class="btn btn-primary btn-sm" href="{{route('season.show',$season->id)}}">Select</a>
                    </div>
                  <h3 class="panel-title" style="vertical-align:middle">{{$season->name}}</h3>
                </div>
                <div class="panel-body">
                    <table class="table borderless" style="border:none;">
                        <tr>
                            <td>
                                <label for="spnWeekCount">Number of Weeks</label>
                                <span id="spnWeekCount">{{$season->weeks->count()}}</span>
                            </td>
                            <td>
                                <label for="spnTourTeamCount">Number of Tour Teams</label>
                                <span>{{$season->tour_teams->count()}}</span>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        {{-- <li>
            <h3></h3>
        </li>
        <li role="separator" class="divider"></li>
        <li>
            
        </li> --}}
        @endforeach
    </div>
    <div class="modal fade" id="newSeasonPopup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title" id="exampleModalLabel">Add New Season</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form class="form" id="modal-form" method="post" action="{{route('season.store')}}">
                        {{ csrf_field() }}
                        <div class="form-group mb-2">
                            <label class="col-sm-3 control-label" for="seasonType">Season Type</label>
                            <select name="seasonType" id="seasonType" class="form-control"
                                    aria-controls="help-pickup">
                                <option value="none">Select type</option>
                                @foreach ($seasonTypes as $seasonType)
                                    <option value='{{$seasonType->id}}'>
                                        {{$seasonType->name}}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group mb-2">
                            <label class="col-sm-3 control-label" for="txbDescription">Description</label>
                            <input class="form-control" type="text" name="seasonDescription" id="seasonDescription">
                        </div>
                        <div class="form-group mb-2">
                            <label class="col-sm-3 control-label" for="seasonStartDate"></label>
                            <input class="form-control" type="date" name="seasonStartDate" id="seasonStartDate">
                        </div>
                        <div class="form-group mb-2">
                            <label class="col-sm-3 control-label" for="seasonEndDate"></label>
                            <input class="form-control" type="date" name="seasonEndDate" id="seasonEndDate">
                        </div>
                        <div class="modal-footer">
                            <button type="reset" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <button type="submit" role="button" class="btn btn-primary" >OK</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')

@endsection

resources/views/tourTeams.blade.php
@extends('layouts.master')

@section('title')
    Tours Page
@endsection

@section('head')

@endsection
@section('content')
    <!--
    <div class="row">
        <div class="form-group mb-2">
            <label class="sr-only" for="season-select">Season Select:</label>
            <select name="season-select" id="season-select" class="form-control"
                    onchange="this.options[this.selectedIndex].value && (window.location = this.options[this.selectedIndex].value);">
                <option value="">Season Select</option>
                @foreach ($seasons as $season)
                    <option value="{{route('tourTeams.show', [$season->id])}}">{{$season->name}}</option>
                @endforeach
            </select>
        </div>
    </div>
    !-->

    <center><label><font size="24">{{$title}}</font></label></center>

    <div class="row">
        <table class="table table-condensed table-striped table-bordered" id="tours-table" style="border-width: thick">
            <thead>
            <tr>

                <th>Edit Team</th>
                <th>Show Title</th>
                <th>Season</th>
                <th>Remove Team</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($tour_teams as $tour_team)

                <tr>


                    <td>
                        <button class="btn btn-primary" data-toggle="modal" onclick="populateTourTeamId({{$tour_team->id}});" data-target="#editTour">{{$tour_team->show_id}} {{$tour_team->show_num}}</button>
                    </td>

                    <td>{{$tour_team->show->show_title}}</td>
                    <td>{{$tour_team->season->name}}</td>
                    <td>
                        <button class="btn btn-primary"><a style="color:white" href={{route('tourTeams.edit', $tour_team->id)}} onclick="return confirm('Delete {{$tour_team->show->show_title}} from the season {{$tour_team->season->name}}?')">Delete</a> </button>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <!--Modal for editing tour -->

        <div class="modal fade" id="editTour" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3 class="modal-title" id="exampleModalLabel">Edit Tour Team</h3>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">



                        <form class="form" id="modal-form" method="post" action="{{route('tourTeams.update', 0)}}">
                            {{ csrf_field() }}
                            {{method_field('PATCH')}}
                            <div class="form-group mb-2">
                                <label for="show-name">New Tour Team Show</label>
                                <select name="show-select" id="show-select" class="form-control">
                                    <option value="none" disabled>Show Select</option>
                                    @foreach ($shows as $show)
                                        <option value='{{$show->abbreviation}}'>
                                            {{$show->show_title}}
                                        </option>
                                    @endforeach
                                </select>
                                <input type="hidden" name="tour-id" id="tour-id" class="form-control-plaintext">
                            </div>


                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">OK</button>
                    </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>


@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('table').DataTable({});
        });

        function populateTourTeamId(id){
            document.getElementById("tour-id").value = id;

        }

    </script>
@endsection