routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});


Auth::routes();

Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::middleware('auth')->group(function(){


    Route::resource('requests', 'ResRequestController');
    Route::view('addRequest','requests/addRequest')->name('addRequest');
    Route::resource('season','SeasonController');
    Route::get('home', 'PresenterController@index')->name('home');
    Route::post('requests-add', 'ResRequestController@getSeasonWeeks')->name('getSeasonWeeks');
    Route::resource('tourTeams', 'TourTeamsController');
    Route::delete('tourTeams', 'TourTeamsController@delete');
    Route::resource('presenters', 'PresenterController');
    Route::resource('contacts', 'ContactController');
    Route::resource('shows','ShowController');
    Route::resource('bookings','BookingController');
    // route::route('bookings','BookingController');
    Route::post('moveBooking', 'BookingController@moveBooking')->name('moveBooking');
    Route::get('createBooking/{seasonId}/{weekId?}/{tourTeamId?}', [
        'as' => 'createBooking', 'uses' => 'BookingController@createBooking']);
    Route::get('deleteBooking/{id}', [
            'as' => 'deleteBooking', 'uses' => 'BookingController@deleteBooking']);
    Route::view('admin','admin')->name('admin');
    Route::view('edit_request','edit_request')->name('edit_request');

});

Route::get('test','Controller@index');

app/Models/Tour_team.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tour_team extends Model
{
    protected $table = 'tour_teams';
    protected $fillable = ['complete','show_id','season_id'];

    public function weeks(){

        return $this->belongsToMany('App\Week','season_weeks');

    }
    public static function display($tour_team)
    {
        return $tour_team->show_id." ".$tour_team->show_num;
    }
    public function show(){
        return $this->hasOne(Show::class, 'abbreviation', 'show_id');
    }
    public function season(){
        return $this->hasOne(Season::class, 'id', 'season_id');
    }
    public static function getShowsBySeason($id){
        $data = Tour_team::where('season_id','=',$id)->get();
        return $data;
    }
    public function bookings()
    {
        return $this->hasMany(Booking::class,'tour_team_id');
    }
    public static function getNumShowsInSeason($id1,$id2){
        $count = Tour_team::where('season_id', '=', $id1)->where("show_id", '=', $id2)->count();
        return $count+1;
    }
}

app/Http/Controllers/TourTeamsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tour_team;
use Illuminate\Http\Request;

class TourTeamsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){

        $data['tour_teams'] = \App\Models\Tour_team::all();
        $data['contacts'] = \App\Models\Contact::all();
        $data['seasons'] = \App\Models\Season::all();
        $data['shows'] = \App\Models\Show::all();
        $data['title'] = "All Tour Teams";

        return view('tourTeams', $data);

    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $data['seasons'] = \App\Models\Season::all();
        $data['shows'] = \App\Models\Show::all();

        return view('tourTeams/create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $tour_team = new Tour_team();
        $tour_team->season_id = $request->input('season');
        $tour_team->show_id = $request->input('show');
        $tour_team->complete = $request->input('complete');

        // Get the current show number for that season.
        $tour_team->show_num = \App\Models\Tour_team::getNumShowsInSeason($tour_team->season_id,$tour_team->show_id);
        $tour_team->save();

        return redirect()->route('tourTeams.show', $tour_team->season_id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['tour_teams'] = Tour_team::getShowsBySeason($id);
        $data['contacts'] = \App\Models\Contact::all();
        $data['seasons'] = \App\Models\Season::all();
        $data['shows'] = \App\Models\Show::all();
        $collection = \App\Models\Season::where('id', "=", $id)->pluck('name');
        $data['title'] = $collection[0];


        return view('tourTeams', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $team_to_delete = Tour_team::where('id', "=", $id)->first();

        $temp = $team_to_delete; // Temp so I can delete.
        $team_to_delete->delete();
        $show_id = $temp->show_id;
        $season_id = $temp->season_id;

        $data = Tour_team::getShowsBySeason($season_id);

        foreach($data as $show){

            if($show->show_id == $show_id && $show->show_num > 1){
                $show->show_num = $show->show_num-1;
                $show->save();
            }
        }

        return redirect()->route('tourTeams.show', $season_id);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tour_id = $request->input('tour-id');

        $tour_team = Tour_team::where('id', "=", $tour_id)->first();

        // Get all old data
        $season_id = $tour_team->season_id;
        $new_show = $request->input('show-select');
        $old_show = $tour_team->show_id;
        $old_num = $tour_team->show_num;

        $data = Tour_team::getShowsBySeason($season_id);

        if($old_show != $new_show){

            $tour_team->show_id = $new_show;
            $tour_team->show_num = \App\Models\Tour_team::getNumShowsInSeason($season_id, $new_show);
            $tour_team->save(); // Save the tour team with the new show num

            $data = Tour_team::getShowsBySeason($season_id);

            foreach($data as $show){

                if($show->show_id == $old_show && $show->show_num > $old_num){
                    $show->show_num = $show->show_num -1;

                    $show->save(); // Save the tour_team with the new show num if changed
                }


            }

        }

        return redirect()->route('tourTeams.show', $season_id);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function destroy($id)
    {


    }

}

resources/views/tourTeams/create.blade.php
@extends('layouts.master')

@section('title')
    Create Tour Team Page
@endsection

@section('content')

<div class="container-fluid">
    <div class="row">
        <form class="form" id="new-team" method="post" action="{{route('tourTeams.store')}}">
            {{ csrf_field() }}
            <div class="form-group mb-2">
                <label for="season">Season:</label>
                <select name="season" id="season" class="form-control">
                    <option value="none">Select Season</option>
                    @foreach ($seasons as $season)
                        <option value='{{$season->id}}'>
                            {{$season->name}}
                        </option>
                    @endforeach
                </select>
            </div>

            <div class="form-group mb-2">
                <label for="show">Show:</label>
                <select name="show" id="show" class="form-control">
                    <option value="none">Select Show</option>
                    @foreach ($shows as $show)
                        <option value='{{$show->abbreviation}}'>
                            {{$show->show_title}}
                        </option>
                    @endforeach
                </select>
            </div>

            <div class="form-group col-md-12">
                <input type="hidden" readonly class="form-control-plaintext" name="complete" id="complete"
                       value = 0>
            </div>
            <button role="button" type="reset" class="btn btn-secondary">Cancel</button>
            <button role="button" type="submit" class="btn btn-primary">OK</button>
        </form>


        </div>
    </div>
</div>

@endsection

@section('scripts')

@endsection

resources/views/tourTeams/newShow.blade.php
@extends('layouts.master')

@section('title')
    Create Show Page
@endsection

@section('content')

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <form class="form" id="new-team" method="post" action="{{route('shows.store')}}">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="abbreviation">Show Abbreviation:</label>
                        <div class="col-sm-9">
                            <input type="text" name="abbreviation" id="abbreviation"
                                   placeholder="Enter Show Abbreviation"
                                   class="input form-control">
                        </div>
                    </div>

                    <div class=form-group>
                        <label class="col-sm-3 control-label" for="show-title">Show Title:</label>
                        <div class="col-sm-9">
                            <input type="text" name="show-title" id="show-title" placeholder="Enter Show Title"
                                   class="input form-control">
                        </div>
                    </div>

                    <div class="form-group">
                        <button type="reset" role="button" class="btn btn-secondary">Cancel</button>
                        <button type="submit" role="button" class="btn btn-primary">Add</button>

                    </div>
                </form>
            </div>
        </div>
    </div>


@endsection

@section('scripts')

@endsection