routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});


Auth::routes();

Route::post('logout','Auth\LoginController@logout')->name('logout');

Route::middleware('auth')->group(function(){


    Route::resource('requests', 'ResRequestController');
    Route::view('addRequest','requests/addRequest')->name('addRequest');
    Route::resource('season','SeasonController');
    Route::get('home', 'PresenterController@index')->name('home');
    Route::post('requests-add', 'ResRequestController@getSeasonWeeks')->name('getSeasonWeeks');
    Route::resource('tourTeams', 'TourTeamsController');
    Route::delete('tourTeams', 'TourTeamsController@delete');
    Route::resource('presenters', 'PresenterController');
    Route::resource('contacts', 'ContactController');
    Route::resource('shows','ShowController');
    Route::resource('bookings','BookingController');
    // route::route('bookings','BookingController');
    Route::post('moveBooking', 'BookingController@moveBooking')->name('moveBooking');
    Route::get('createBooking/{seasonId}/{weekId?}/{tourTeamId?}', [
        'as' => 'createBooking', 'uses' => 'BookingController@createBooking']);
    Route::get('deleteBooking/{id}', [
            'as' => 'deleteBooking', 'uses' => 'BookingController@deleteBooking']);
    Route::view('admin','admin')->name('admin');
    Route::view('edit_request','edit_request')->name('edit_request');

});

Route::get('test','Controller@index');

app/Models/Presenter.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Presenter extends Model
{
    protected $table = 'presenters';
    protected $fillable = ['presenter_name','is_fly_school'];

    public function contacts(){

        return $this->belongsToMany(Contact::class, 'presenter_contacts')->withPivot('contact_type_id');

    }
    public function primary_contact(){

        return $this->belongsToMany(Contact::class, 'presenter_contacts')->withPivot('contact_type_id')->where('contact_type_id', Contact_type::getPrimaryContactId());

    }
    public function res_requests(){

        return $this->belongsToMany(Res_requests::class, 'res_requests' );

    }
    // public function location()
    // {
    //     return   $this->belongsToMany(Contact::class, 'presenter_contacts')->withPivot('contact_type_id')->where('contact_type_id', Contact_type::getPrimaryContactId())->first();
    //     //dd($contact);
    //     return $contact->city . ", ". $contact->state_id;
    // }
    public function presenter_color()
    {
        return $this->belongsToMany(Contact::class, 'presenter_contacts')->withPivot('contact_type_id')->where('contact_type_id', Contact_type::getPrimaryContactId())->first()->state()->region();
        // return \DB::table('presenter_contacts')
        // ->select('color')
        // ->join('contacts','contacts.id','=','presenter_contacts.contact_id')
        // ->join('states','states.id','=','contacts.id')
        // ->join('regions','regions.id','=','states.region_id')
        // ->where('presenter_contacts.contact_type_id', Contact_type::getPrimaryContactId())
        // ->where('presenter_contacts.presenter_id',$pesenter_id)
        // ->get();
        //return Presenter::find($pesenter_id)->primary_contact->state->region->region_color;
    }

    public static function PastShows($presenter_id,$season_id)
    {
        $date = Season::where('id',$season_id)->get();
        $date = ($date->first()->weeks->sortBy('start_date')->first()->start_date);
        $result = \DB::select(\DB::raw("select GROUP_CONCAT(x.showName order by x.end_date desc) as past_shows
        from 
        (
        select b.presenter_id,CONCAT(tt.show_id ,' ',tt.show_num) as showName, w.end_date
        from bookings b 
        join tour_teams tt on tt.id = b.tour_team_id
        join weeks w on w.id = b.week_id
        where b.presenter_id = :presenterId
        and w.end_date <= :date
        union 
        select :presenterIdFixed as presenter_id, null as showName, ''as end_date 
        )x
        group by x.presenter_id"), array(
            'presenterId' => $presenter_id,
            'date' => $date,
            'presenterIdFixed' => $presenter_id,
          ));
        return $result;
    }
}

app/Http/Controllers/PresenterController.php
<?php

namespace App\Http\Controllers;

use App\Models\Contact;
use App\Models\Presenter;
use App\Models\Presenter_contact;
use App\Models\State;
use Carbon\Carbon;
use Illuminate\Http\Request;

class PresenterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if (request()->filled('presenter-name')) {
            $data['presenters'] = Presenter::where('presenter_name', 'like',"%".request()->get('presenter-name')."%" )->get();

        } else {
            $data['presenters'] = Presenter::all();
        }

        return view('presenters', $data);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data['states'] = State::all();

        return view('presenters/create', $data);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $contact = new Contact();
        $contact->contact_name = $request->input('contact-name');
        $contact->email = $request->input('email');
        $contact->address = $request->input('address');
        $contact->city = $request->input('city');
        $contact->zip_code = $request->input('zip-code');
        $contact->state_id = $request->input('state');
        $contact->save();

        $presenter = new Presenter();
        $presenter->presenter_name = $request->input('presenter-name');
        $presenter->is_fly_school = $request->input('fly-school');
        $presenter->save();


        $presenter->primary_contact()->attach($contact->id);
        //$presenter->primary_contact()->save($contact);

        return redirect('presenters');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/presenters/create.blade.php
@extends('layouts.master')

@section('title')
    Create Presenter Page
@endsection

@section('content')


    <div class="container " id="collapseForm">
        <div class="row">
            <div class="col-lg-12">
                <form class="form-horizontal" method="post" action="{{route('presenters.store')}}">
                    {{ csrf_field() }}
                    <h2>Presenter Information</h2>
                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="presenter-name">Presenter Name:</label>
                        <div class="col-sm-9">
                            <input name="presenter-name" id="presenter-name" placeholder="Enter Presenter Name"
                                   class="input form-control">
                        </div>
                    </div>

                   <div class="form-group" style="visibility: hidden">
                        <label class="col-sm-3 control-label" for="fly-school">Fly School:</label>
                        <div class="col-sm-9">
                            <select name="fly-school" id="fly-school" class="form-control" aria-controls="help-pickup">
                                <option value="none">Is fly school?</option>
                                <option value='1'>
                                    True
                                </option>
                                <option selected="selected" value='0'>
                                    False
                                </option>
                            </select>
                            <p id="help-pickup" class="help-block" aria-live="polite"></p>
                        </div>
                    </div>

                    <h2>Primary Contact Information</h2>

                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="contact-name">Contact Name:</label>
                        <div class="col-sm-9">
                            <input type="text" name="contact-name" id="contact-name" placeholder="Contact Name"
                                   class="input form-control"
                                   data-format="1">
                        </div>
                    </div>

                    <div class=form-group>
                        <label class="col-sm-3 control-label" for="email">Email:</label>
                        <div class="col-sm-9">
                            <input type="text" name="email" id="email" placeholder="Enter Email"
                                   class="input form-control"
                                   data-format="1">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="address">Address:</label>
                        <div class="col-sm-9">
                            <input type="text" name="address" id="address" placeholder="Enter Address"
                                   class="input form-control"
                                   data-format="1">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="city">City:</label>
                        <div class="col-sm-9">
                            <input type="text" name="city" id="city" placeholder="Enter City"
                                   class="input form-control"
                                   data-format="1">
                        </div>
                    </div>



                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="state">State:</label>
                        <div class="col-sm-9">
                            <select name="state" id="state" class="form-control" aria-controls="help-pickup">
                                <option value="none">Select State</option>
                                @foreach ($states as $state)
                                    <option value='{{$state->id}}'>
                                        {{$state->abbreviation}}
                                    </option>
                                @endforeach
                            </select>
                            <p id="help-pickup" class="help-block" aria-live="polite"></p>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-3 control-label" for="zip-code">Zip Code:</label>
                        <div class="col-sm-9">
                            <input type="text" name="zip-code" id="zip-code" placeholder="Enter Zip Code"
                                   class="input form-control"
                                   data-format="1">
                        </div>
                    </div>

                    <div class=form-group>
                        <button type="reset" role="button" class="col-sm-2 button btn btn-primary">Cancel</button>
                        <button type="submit" role="button" class="col-sm-2 button btn btn-primary pull-right">Add
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    <!--TESTING ADDING A NEW CONTACT TO AN EXISTING PRESENTER-->






@endsection

@section('scripts')

@endsection

resources/views/presenters/createContact.blade.php
@extends('layouts.master')

@section('title')
    Create Contact Page
@endsection

@section('content')
    <div class="container " id="collapseForm">
    <div class="row">
        <div class="col-lg-12">
            <form class="form-horizontal" method="post" action="{{route('contacts.store')}}">
                {{ csrf_field() }}
                <h2>Presenter Information</h2>
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="presenter-name">Presenter:</label>
                    <div class="col-sm-9">
                        <select name="presenter-name" id="presenter-name" class="form-control"
                                aria-controls="help-pickup">
                            <option value="none">Select Presenter</option>
                            @foreach ($presenters as $presenter)
                                <option value='{{$presenter->id}}'>
                                    {{$presenter->presenter_name}}
                                </option>
                            @endforeach
                        </select>
                        <p id="help-pickup" class="help-block" aria-live="polite"></p>
                    </div>
                </div>

                <h2>New Contact Information</h2>

                <div class="form-group">
                    <label class="col-sm-3 control-label" for="contact-name">Contact Name:</label>
                    <div class="col-sm-9">
                        <input type="text" name="contact-name" id="contact-name" placeholder="Contact Name"
                               class="input form-control"
                               data-format="1">
                    </div>
                </div>

                <div class=form-group>
                    <label class="col-sm-3 control-label" for="email">Email:</label>
                    <div class="col-sm-9">
                        <input type="text" name="email" id="email" placeholder="Enter Email"
                               class="input form-control"
                               data-format="1">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label" for="address">Address:</label>
                    <div class="col-sm-9">
                        <input type="text" name="address" id="address" placeholder="Enter Address"
                               class="input form-control"
                               data-format="1">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label" for="city">City:</label>
                    <div class="col-sm-9">
                        <input type="text" name="city" id="city" placeholder="Enter City"
                               class="input form-control"
                               data-format="1">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label" for="zip-code">Zip Code:</label>
                    <div class="col-sm-9">
                        <input type="text" name="zip-code" id="zip-code" placeholder="Enter Zip Code"
                               class="input form-control"
                               data-format="1">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label" for="state">State:</label>
                    <div class="col-sm-9">
                        <select name="state" id="state" class="form-control" aria-controls="help-pickup">
                            <option value="none">Select State</option>
                            @foreach ($states as $state)
                                <option value='{{$state->id}}'>
                                    {{$state->abbreviation}}
                                </option>
                            @endforeach
                        </select>
                        <p id="help-pickup" class="help-block" aria-live="polite"></p>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label" for="type">Contact Type:</label>
                    <div class="col-sm-9">
                        <select name="type" id="type" class="form-control" aria-controls="help-pickup">
                            <option value="none">Select Type</option>
                            @foreach ($contactTypes as $type)
                                <option value='{{$type->id}}'>
                                    {{$type->type_name}}
                                </option>
                            @endforeach
                        </select>
                        <p id="help-pickup" class="help-block" aria-live="polite"></p>
                    </div>
                </div>

                <div class=form-group>
                    <button type="reset" role="button" class="col-sm-2 button btn btn-primary">Cancel</button>
                    <button type="submit" role="button" class="col-sm-2 button btn btn-primary pull-right">Add
                    </button>
                </div>
            </form>
        </div>
    </div>
    </div>
@endsection

@section('scripts')

@endsection